Contexts\OneTimePassword\Domain\Entities\OneTimePassword:
  type: entity
  table: one_time_passwords
  id:
    oneTimePasswordId:
      type: OneTimePasswordId
      column: id
  fields:
    type:
      type: string
      enumType: Contexts\OneTimePassword\Application\Enums\OneTimePasswordType
    code:
      type: string
    attempts:
      column: attempts
      type: integer
      default: 0
    maxAttempts:
      column: max_attempts
      type: integer
    expirationDate:
      column: expiration_date
      type: datetime
    confirmedAt:
      column: confirmed_at
      type: datetime
      nullable: true
    deletedAt:
      column: deleted_at
      type: datetime
      nullable: true
    createdAt:
      column: created_at
      type: datetime
      nullable: false
      gedmo:
        timestampable:
          on: create
    updatedAt:
      column: updated_at
      type: datetime
      nullable: false
      gedmo:
        timestampable:
          on: update
  embedded:
    subjectId:
      class: Contexts\OneTimePassword\Domain\ValueObjects\SubjectId
      columnPrefix: false
